RESOLUTIONS = [i * (10 ** j) for j in range(3, 7) for i in range(1, 10)]

rule all:
    input:
        expand(
            '{genome}_{size}bp.bed',
            genome=['hg19', 'hg38'], size=RESOLUTIONS
        )

rule mkwindows:
    input:
        '{genome}.bed'
    output:
        '{genome}_{size}bp.bed'
    shell:
        'bedtools makewindows -b {input} -w {wildcards.size} > {output}'
