# ==============================================================================
# Environment
# ==============================================================================
import os.path as path
import pandas as pd

CONFIG = pd.read_csv(
    path.join("..", "..", "Data", "External", "LowC_Samples_Data_Available.tsv"),
    sep="\t",
    header=0
)
SAMPLES = ["PCa" + str(i) for i in CONFIG.loc[CONFIG.Include == "Yes", "Sample ID"]]

BREAK_DIR = path.join("..", "2019-07-24_breakfinder", "Breakpoints", "Default")
TAD_DIR = path.join("..", "..", "results", "2020-08-29_TADs-downsampled", "Aggregated-TADs")
GRAPH_DIR = path.join("..", "..", "results", "2020-02-19_chromoplexy", "Graphs")

RES_DIR = path.join("..", "..", "results", "2020-02-19_sv-disruption-TADs")
PLOT_DIR = path.join(RES_DIR, "Plots")

PLOT_EXTS = ["png", "pdf"]

# ==============================================================================
# Meta Rules
# ==============================================================================
rule all:
    input:
        path.join(RES_DIR, "sv-disruption-tests.TADs.tsv"),
        path.join(RES_DIR, "sv-disruption-tests.TADs.counts.tsv"),
        expand(
            path.join(PLOT_DIR, "tads.count.{ext}"),
            ext=PLOT_EXTS
        ),

# ==============================================================================
# Rules
# ==============================================================================
rule altered_TADs:
    input:
        script = "altered-tads.py",
        graph = path.join(GRAPH_DIR, "breakpoints.all-samples.p"),
        test = path.join(GRAPH_DIR, "sv-disruption-tests.tsv"),
        breaks = path.join(GRAPH_DIR, "sv-breakpoints.tsv"),
        tads = expand(
            path.join(TAD_DIR, "separated-TADs", "{sample}.40000bp.w_3.domains.bed"),
            sample=SAMPLES
        ),
    output:
        path.join(RES_DIR, "sv-disruption-tests.TADs.tsv"),
    shell:
        "python {input.script}"

rule plot_tads:
    input:
        script = "plot-tads.R",
        data = path.join(RES_DIR, "sv-disruption-tests.TADs.tsv"),
    output:
        path.join(RES_DIR, "sv-disruption-tests.TADs.counts.tsv"),
        expand(
            path.join(PLOT_DIR, "tads.count.{ext}"),
            ext=PLOT_EXTS
        ),
    shell:
        "Rscript {input.script}"
