import pandas as pd
import os.path as path

# ==============================================================================
# Rules
# ==============================================================================
rule create_digest_ref:
    input:
        path.join('..', '..', 'External', 'hg19_Bowtie2Index', 'genome.fa')
    output:
        'Digest_hg19_hindIII_None.txt'
    params:
        '--genome hg19 --re1 A^AGCTT,HindIII'
    shell:
        'hicup_digester {params} {input}; mv Digest_hg19_hindIII_None*.txt Digest_hg19_hindIII_None.txt'
