# =============================================================================
# Configuration
# =============================================================================
import pandas as pd
import os.path as path

CONFIG = pd.read_csv("config.tsv", index_col=False, sep="\t")
CONFIG = CONFIG.loc[CONFIG.Include == "Yes", :]
SAMPLES = CONFIG["Sample_ID"].tolist()

CONTACT_DIR = path.join("..", "..", "results", "2020-08-29_TADs-downsampled", "downsampled-contacts")
CMPMT_DIR = path.join("..", "..", "results", "2021-03-03_compartments", "Compartments")

# =============================================================================
# Meta Rules
# =============================================================================
rule all:
	input:
		path.join(RES_DIR, "gc-content-phase.bedGraph"),
		expand(
			path.join(CMPMT_DIR, "{sample}.compartments.cis.{ext}"),
			sample=SAMPLES,
			ext=["bw", "lam.txt", "vecs.tsv"],
		),

# =============================================================================
# Rules
# =============================================================================
rule gc_a_phase:
	input:
		"get_a_phase.py",
	output:
		path.join(RES_DIR, "gc-content-phase.bedGraph"),
	shell:
		"python {input}"

rule compartments:
	input:
		cool = path.join(CONTACT_DIR, "{sample}.300000000.40000bp.cool"),
		phase = path.join(RES_DIR, "gc-content-phase.bedGraph"),
	output:
		path.join(CMPMT_DIR, "{sample}.compartments.cis.bw"),
		path.join(CMPMT_DIR, "{sample}.compartments.cis.lam.txt"),
		path.join(CMPMT_DIR, "{sample}.compartments.cis.vecs.tsv"),
	params:
		"--bigwig",
	shell:
		"cooltools call-compartments {params} --reference-track {input.phase} -o {CMPMT_DIR}/{wildcards.sample}.compartments {input.cool}"
