# ==============================================================================
# Configuration
# ==============================================================================
import pandas as pd
import os.path as path

CONFIG = pd.read_csv(
    path.join("..", "2020-02-19_chromoplexy", "Graphs", "sv-disruption-tests.tsv"),
    sep="\t",
    index_col=False,
)

TEST_IDS = CONFIG.test_ID.tolist()

PLOT_DIR = "Plots"

# ==============================================================================
# Meta Rules
# ==============================================================================
rule all:
    input:
        "results.genes.tsv",
        "results.transcripts.tsv",
        "t2e-comparison.genes.tsv",
        "t2e-comparison.transcripts.tsv",
        "sleuth-object.rds",
        expand(
            path.join("sleuth", "test_{test_ID}.{ext}"),
            test_ID=TEST_IDS,
            ext=[
                "genes.all.tsv",
                "transcripts.all.tsv",
                "genes.tested.tsv",
                "transcripts.tested.tsv",
                "sleuth-object.rds"
            ],
        ),
        path.join(PLOT_DIR, "expression.png"),
        path.join(PLOT_DIR, "expression.pdf"),
        path.join(PLOT_DIR, "event-changes.png"),
        path.join(PLOT_DIR, "event-changes.pdf"),
        path.join(PLOT_DIR, "event-changes.labelled.png"),
        path.join(PLOT_DIR, "event-changes.labelled.pdf"),
        "1sample-results.tsv",
        path.join(PLOT_DIR, "gene-exprs.ERG-TMPRSS2.png"),
        path.join(PLOT_DIR, "gene-exprs.ERG-TMPRSS2.pdf"),
        path.join(PLOT_DIR, "gene-exprs.ZNF516-PMEPA1.png"),
        path.join(PLOT_DIR, "gene-exprs.ZNF516-PMEPA1.pdf"),
        path.join(PLOT_DIR, "tx-exprs.BRAF.png"),
        path.join(PLOT_DIR, "tx-exprs.BRAF.pdf"),
        path.join(PLOT_DIR, "event-changes.summary.png"),
        path.join(PLOT_DIR, "event-changes.summary.pdf"),
        path.join(PLOT_DIR, "event-changes.contact.png"),
        path.join(PLOT_DIR, "event-changes.contact.pdf"),

# ==============================================================================
# Rules
# ==============================================================================
rule t2e_comp:
    input:
        script = "t2e-dge.R",
    output:
        "results.genes.tsv",
        "results.transcripts.tsv",
        "t2e-comparison.genes.tsv",
        "t2e-comparison.transcripts.tsv",
        "sleuth-object.rds",
    shell:
        "Rscript {input.script}"

rule plot_erg:
    input:
        script = "plot-t2e.R",
        sleuth = "sleuth-object.rds",
        data = "t2e-comparison.transcripts.tsv"
    output:
        "outfile"
    shell:
        "python {input.script} {input.data} -o {output}"

rule sv_test_comp:
    input:
        script = "1sample-dge.sleuth.R",
    output:
        path.join("sleuth", "test_{test_ID}.genes.all.tsv"),
        path.join("sleuth", "test_{test_ID}.transcripts.all.tsv"),
        path.join("sleuth", "test_{test_ID}.genes.tested.tsv"),
        path.join("sleuth", "test_{test_ID}.transcripts.tested.tsv"),
        path.join("sleuth", "test_{test_ID}.sleuth-object.rds"),
    shell:
        "Rscript {input.script} {wildcards.test_ID}"

rule plot_dge_1samp:
    input:
        script = "plot-1sample-dge.sleuth.R",
        data = expand(
            path.join("sleuth", "test_{test_ID}.{ext}"),
            test_ID=TEST_IDS,
            ext=[
                "genes.all.tsv",
                "transcripts.all.tsv",
                "genes.tested.tsv",
                "transcripts.tested.tsv",
                "sleuth-object.rds"
            ],
        ),
    output:
        path.join(PLOT_DIR, "expression.png"),
        path.join(PLOT_DIR, "expression.pdf"),
        path.join(PLOT_DIR, "event-changes.png"),
        path.join(PLOT_DIR, "event-changes.pdf"),
        path.join(PLOT_DIR, "event-changes.labelled.png"),
        path.join(PLOT_DIR, "event-changes.labelled.pdf"),
        "1sample-results.tsv",
    shell:
        "Rscript {input.script}"

rule plot_znf516_pmepa1_t2e:
    input:
        script = "plot-gene-exprs.R",
        data = expand(
            path.join("sleuth", "test_{test_ID}.{ext}"),
            test_ID=[42, 43, 45, 46],
            ext=[
                "genes.all.tsv",
                "transcripts.all.tsv",
                "genes.tested.tsv",
                "transcripts.tested.tsv",
                "sleuth-object.rds"
            ],
        ),
    output:
        path.join(PLOT_DIR, "gene-exprs.ERG-TMPRSS2.png"),
        path.join(PLOT_DIR, "gene-exprs.ERG-TMPRSS2.pdf"),
        path.join(PLOT_DIR, "gene-exprs.ZNF516-PMEPA1.png"),
        path.join(PLOT_DIR, "gene-exprs.ZNF516-PMEPA1.pdf"),
    shell:
        "Rscript {input.script}"

rule plot_braf:
    input:
        script = "plot-tx-exprs.R",
        data = expand(
            path.join("sleuth", "test_{test_ID}.{ext}"),
            test_ID=[201],
            ext=[
                "genes.all.tsv",
                "transcripts.all.tsv",
                "genes.tested.tsv",
                "transcripts.tested.tsv",
                "sleuth-object.rds"
            ],
        ),
    output:
        path.join(PLOT_DIR, "tx-exprs.BRAF.png"),
        path.join(PLOT_DIR, "tx-exprs.BRAF.pdf"),
    shell:
        "Rscript {input.script}"

rule sv_annotation:
    input:
        script = "plot-sv-changes.R",
        data = "summary-sv-disruption-annotation.tsv",
    output:
        path.join(PLOT_DIR, "event-changes.summary.png"),
        path.join(PLOT_DIR, "event-changes.summary.pdf"),
        path.join(PLOT_DIR, "event-changes.contact.png"),
        path.join(PLOT_DIR, "event-changes.contact.pdf"),
    shell:
        "Rscript {input.script}"
